### ISSUE TITLE
Can't always place a block

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/terra-test-game#4]
In some situations you can't place a block in location XYZ if you click on a certain block face, for example vertical block face. But if you click on another block face you can get a block in that same XYZ space.

![https://i.snag.gy/m2ns35.jpg](https://i.snag.gy/m2ns35.jpg)

**Comment by Pawlost** [comment]
We need more testing for this because I dont get this bug

**Comment by Pilvinen** [comment]
It happens only rarely. I will see if I can repeat it in the latest version.

**Comment by Pawlost** [comment]
This bug is related to this https://github.com/starandserpent/Terra/issues/45 terra issue.
